### ISSUE TITLE
Malformed Packet after MySQL server restart

### ISSUE THREAD

**Issue by jpascal** [Philio/GoMySQL#1]
My check MySQL ready function:

```
if (!MySQL.Ping()){
    Log("MySQL not open")
    if(!MySQL.Connect("127.0.0.1", "user", "password", "mysql")) {
        Log("Error: %v",MySQL.Error)
        return false
    }
    Log("MySQL ready")
}
return true
```

call CheckReady()

2010/04/24 12:16:55 MySQL not open
2010/04/24 12:16:55 Connect called
2010/04/24 12:16:55 Connected using TCP/IP
2010/04/24 12:16:55 [0] Received init packet from server
2010/04/24 12:16:55 [1] Sent auth packet to server
2010/04/24 12:16:55 [2] Received ok packet from server
2010/04/24 12:16:55 Current result set saved
2010/04/24 12:16:55 MySQL Ready

restart MySQL server

2010/04/24 12:17:13 MySQL not open
2010/04/24 12:17:13 Close called
2010/04/24 12:17:13 Connect called
2010/04/24 12:17:13 Error: Malformed Packet

How correct to restore connections after broke?

**Comment by Philio** [comment]
Thanks for the report, the next release will support auto-reconnect, I'm just figuring out the best way to implement it.

It should be done sometime this weekend.

**Comment by Philio** [comment]
It seams the issue you're having is actually because Close() fails. This is because it performs a graceful closure of the connection to the server.

Firstly the close command is sent (which obviously relies on a working connection) then the tcp link or socket is closed. If the connection was closed by the server side what actually happens is this:
1. Close sends command, which fails generating the malformed packet error, returns false.
2. Connect is called but thinks it is already connected so returns false immediately.

I've not decided how best to implement auto-reconnect, so will push to release a version with the function MySQL.Reconnect() added which forces down the connection and reconnects properly.

**Comment by Philio** [comment]
I've just pushed the updates to release (version 0.1.12) which has the Reconnect() function.
