### ISSUE TITLE
Prepared statement repeat execute returns error

### ISSUE THREAD

**Issue by Philio** [Philio/GoMySQL#7]
stmt.BindParams(...)
stmt.Execute()
stmt.Execute()

Returns:

Error #1210 Incorrect arguments to mysqld_stmt_execute

**Comment by thomaslee** [comment]
ER_WRONG_ARGUMENTS seems to be triggered in sql_prepare.cc in the MySQL source code. Still investigating exactly how/where/why this is happening.

**Comment by Philio** [comment]
It's fine if params are rebound, but doesn't seem to work otherwise.
I did play around a bit with this one the other day but it's possible the other issue was hindering my efforts, will run the same tests again with the fix you added yesterday and see if it makes a difference.

**Comment by thomaslee** [comment]
See here:

http://forge.mysql.com/wiki/MySQL_Internals_ClientServer_Protocol#Execute_Packet_.28Tentative_Description.29

As near as I can tell, the error you're seeing is because you're passing  pkt.newParamBound == 0 yet still sending through parameter data.

That part's easy to fix, just a bitch to track down.

Once you resolve that, there's another bug in the response handling that causes GoMySQL to "hang" (stuck in a processing loop due to bad flags I think -- similar to #6). Investigating that one now. Hopefully have a patch to fix this all later tonight.

**Comment by thomaslee** [comment]
Scratch that, I had simply forgotten to pull in the fix for #6 before creating this branch.

Now getting an OK packet, but no rows in the result set. Hmm.

**Comment by thomaslee** [comment]
Argh. I think I've made it worse. Getting OK packets sometimes, and bad sequence numbers others.

Will come back to this one again later.

**Comment by thomaslee** [comment]
Have a working fix for this now (honest!) but I've broken Reset() in the process. Investigating ...

**Comment by thomaslee** [comment]
I think the Reset() issue is unrelated -- should we expect a response for the server for a COM_STMT_RESET command? I would've thought so...

**Comment by thomaslee** [comment]
Confirmed the issue with Reset() -- see #25.

**Comment by thomaslee** [comment]
Oh and a fix for this particular issue in #22 :)

**Comment by Philio** [comment]
Cheers Tom, will review later and run my tests on it as well.

**Comment by Philio** [comment]
Fix applied to master (0.2.4-dev)
